
import AbstractClasses.MartialArt;
import Clasess.loggers.MemoryLogger;
import Clasess.player.Player;
import Factories.MartialArtFactory;
import static com.sun.source.util.DocTrees.instance;
import java.util.ArrayList;


public class Principal extends javax.swing.JPanel {

    ArrayList<MartialArt> martialStrategies;
    MemoryLogger logger;
    Player player1;
    Player player2;

    public Principal() {
        
        initComponents();    
        ArrayList<MartialArt> martialStrategies = new ArrayList<>();
        
        MemoryLogger logger = new MemoryLogger();

        Player player1 = new Player.PlayerBuilder()
                .setName("John")
                .setMartialArts(MartialArtFactory.getMartialArts())
                .setHealth(200)
                .setLoggerService(logger)
                .build();

        Player player2 = new Player.PlayerBuilder()
                .setName("Ethan")
                .setMartialArts(MartialArtFactory.getMartialArts())
                .setHealth(200)
                .setLoggerService(logger)
                .build();

        player1.attack(player2, 1);
        player2.randomAttack(player1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ArteMarcialName1_J1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArteMarcialName3_J1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ArteMarcialName2_J1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ArteMarcialName1_J2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ArteMarcialName2_J2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ArteMarcialName3_J2 = new javax.swing.JTextArea();
        J1label = new javax.swing.JLabel();
        J2label = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Movimientos3_J1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Movimientos1_J1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Movimientos2_J1 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Movimientos1_J2 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Movimientos2_J2 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        Movimientos3_J2 = new javax.swing.JTextArea();
        ImagenAM_J1 = new javax.swing.JPanel();
        Ataque_J1 = new javax.swing.JButton();
        Ataque_J2 = new javax.swing.JButton();
        GeneradorCombo_J1 = new javax.swing.JToggleButton();
        GeneradorCombo_J2 = new javax.swing.JToggleButton();
        ImagenAM_J3 = new javax.swing.JPanel();
        VidaYGolpes_J1 = new javax.swing.JButton();
        VidaYGolpes_J2 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        InfoBox_J1 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        InfoBox_J2 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        Vida_J1 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        Vida_J2 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        DescripcionAM_J1 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        DescripcionAM_J2 = new javax.swing.JTextArea();
        AsignarJ2 = new javax.swing.JButton();
        AtacarseButton1 = new javax.swing.JButton();
        AsignarJ1 = new javax.swing.JButton();
        SeleccionarAM_J1 = new javax.swing.JButton();
        SeleccionarAM_J2 = new javax.swing.JButton();

        ArteMarcialName1_J1.setColumns(20);
        ArteMarcialName1_J1.setRows(5);
        jScrollPane1.setViewportView(ArteMarcialName1_J1);

        ArteMarcialName3_J1.setColumns(20);
        ArteMarcialName3_J1.setRows(5);
        jScrollPane2.setViewportView(ArteMarcialName3_J1);

        ArteMarcialName2_J1.setColumns(20);
        ArteMarcialName2_J1.setRows(5);
        jScrollPane3.setViewportView(ArteMarcialName2_J1);

        ArteMarcialName1_J2.setColumns(20);
        ArteMarcialName1_J2.setRows(5);
        jScrollPane4.setViewportView(ArteMarcialName1_J2);

        ArteMarcialName2_J2.setColumns(20);
        ArteMarcialName2_J2.setRows(5);
        jScrollPane5.setViewportView(ArteMarcialName2_J2);

        ArteMarcialName3_J2.setColumns(20);
        ArteMarcialName3_J2.setRows(5);
        jScrollPane6.setViewportView(ArteMarcialName3_J2);

        J1label.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        J1label.setText("JUGADOR 1");

        J2label.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        J2label.setText("JUGADOR 2");

        Movimientos3_J1.setColumns(20);
        Movimientos3_J1.setRows(5);
        jScrollPane7.setViewportView(Movimientos3_J1);

        Movimientos1_J1.setColumns(20);
        Movimientos1_J1.setRows(5);
        jScrollPane8.setViewportView(Movimientos1_J1);

        Movimientos2_J1.setColumns(20);
        Movimientos2_J1.setRows(5);
        jScrollPane9.setViewportView(Movimientos2_J1);

        Movimientos1_J2.setColumns(20);
        Movimientos1_J2.setRows(5);
        jScrollPane10.setViewportView(Movimientos1_J2);

        Movimientos2_J2.setColumns(20);
        Movimientos2_J2.setRows(5);
        jScrollPane11.setViewportView(Movimientos2_J2);

        Movimientos3_J2.setColumns(20);
        Movimientos3_J2.setRows(5);
        jScrollPane12.setViewportView(Movimientos3_J2);

        ImagenAM_J1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout ImagenAM_J1Layout = new javax.swing.GroupLayout(ImagenAM_J1);
        ImagenAM_J1.setLayout(ImagenAM_J1Layout);
        ImagenAM_J1Layout.setHorizontalGroup(
            ImagenAM_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        ImagenAM_J1Layout.setVerticalGroup(
            ImagenAM_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        Ataque_J1.setText("Atacar");
        Ataque_J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ataque_J1ActionPerformed(evt);
            }
        });

        Ataque_J2.setText("Atacar");
        Ataque_J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ataque_J2ActionPerformed(evt);
            }
        });

        GeneradorCombo_J1.setText("Generar combo 3-6 golpes");

        GeneradorCombo_J2.setText("Generar combo 3-6 golpes");

        ImagenAM_J3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout ImagenAM_J3Layout = new javax.swing.GroupLayout(ImagenAM_J3);
        ImagenAM_J3.setLayout(ImagenAM_J3Layout);
        ImagenAM_J3Layout.setHorizontalGroup(
            ImagenAM_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        ImagenAM_J3Layout.setVerticalGroup(
            ImagenAM_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        VidaYGolpes_J1.setText("Actualizar Vida y Golpes");

        VidaYGolpes_J2.setText("Actualizar Vida y Golpes");

        InfoBox_J1.setColumns(20);
        InfoBox_J1.setRows(5);
        jScrollPane13.setViewportView(InfoBox_J1);

        InfoBox_J2.setColumns(20);
        InfoBox_J2.setRows(5);
        jScrollPane14.setViewportView(InfoBox_J2);

        Vida_J1.setColumns(20);
        Vida_J1.setRows(5);
        jScrollPane15.setViewportView(Vida_J1);

        Vida_J2.setColumns(20);
        Vida_J2.setRows(5);
        jScrollPane16.setViewportView(Vida_J2);

        DescripcionAM_J1.setColumns(20);
        DescripcionAM_J1.setRows(5);
        jScrollPane17.setViewportView(DescripcionAM_J1);

        DescripcionAM_J2.setColumns(20);
        DescripcionAM_J2.setRows(5);
        jScrollPane18.setViewportView(DescripcionAM_J2);

        AsignarJ2.setText("J2 Re Asignar");
        AsignarJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarJ2ActionPerformed(evt);
            }
        });

        AtacarseButton1.setText("Atacarse");
        AtacarseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarseButton1ActionPerformed(evt);
            }
        });

        AsignarJ1.setText("J1 Re Asignar");
        AsignarJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarJ1ActionPerformed(evt);
            }
        });

        SeleccionarAM_J1.setText("Seleccionar Arte Marcial");
        SeleccionarAM_J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarAM_J1ActionPerformed(evt);
            }
        });

        SeleccionarAM_J2.setText("Seleccionar Arte Marcial");
        SeleccionarAM_J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarAM_J2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(J1label, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(VidaYGolpes_J1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(Ataque_J1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SeleccionarAM_J1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(GeneradorCombo_J1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(ImagenAM_J3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AsignarJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AsignarJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AtacarseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SeleccionarAM_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(J2label, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GeneradorCombo_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Ataque_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(VidaYGolpes_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ImagenAM_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(AtacarseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(AsignarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AsignarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J1label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J2label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SeleccionarAM_J1)
                                            .addComponent(SeleccionarAM_J2))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GeneradorCombo_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GeneradorCombo_J2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Ataque_J1)
                                            .addComponent(Ataque_J2)))
                                    .addComponent(ImagenAM_J3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VidaYGolpes_J1)
                                    .addComponent(VidaYGolpes_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ImagenAM_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Ataque_J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ataque_J1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ataque_J1ActionPerformed

    private void Ataque_J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ataque_J2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ataque_J2ActionPerformed

    private void AsignarJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarJ2ActionPerformed

    private void AtacarseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarseButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtacarseButton1ActionPerformed

    private void AsignarJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarJ1ActionPerformed

    private void SeleccionarAM_J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarAM_J1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarAM_J1ActionPerformed

    private void SeleccionarAM_J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarAM_J2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarAM_J2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ArteMarcialName1_J1;
    private javax.swing.JTextArea ArteMarcialName1_J2;
    private javax.swing.JTextArea ArteMarcialName2_J1;
    private javax.swing.JTextArea ArteMarcialName2_J2;
    private javax.swing.JTextArea ArteMarcialName3_J1;
    private javax.swing.JTextArea ArteMarcialName3_J2;
    private javax.swing.JButton AsignarJ1;
    private javax.swing.JButton AsignarJ2;
    private javax.swing.JButton AtacarseButton1;
    private javax.swing.JButton Ataque_J1;
    private javax.swing.JButton Ataque_J2;
    private javax.swing.JTextArea DescripcionAM_J1;
    private javax.swing.JTextArea DescripcionAM_J2;
    private javax.swing.JToggleButton GeneradorCombo_J1;
    private javax.swing.JToggleButton GeneradorCombo_J2;
    private javax.swing.JPanel ImagenAM_J1;
    private javax.swing.JPanel ImagenAM_J3;
    private javax.swing.JTextArea InfoBox_J1;
    private javax.swing.JTextArea InfoBox_J2;
    private javax.swing.JLabel J1label;
    private javax.swing.JLabel J2label;
    private javax.swing.JTextArea Movimientos1_J1;
    private javax.swing.JTextArea Movimientos1_J2;
    private javax.swing.JTextArea Movimientos2_J1;
    private javax.swing.JTextArea Movimientos2_J2;
    private javax.swing.JTextArea Movimientos3_J1;
    private javax.swing.JTextArea Movimientos3_J2;
    private javax.swing.JButton SeleccionarAM_J1;
    private javax.swing.JButton SeleccionarAM_J2;
    private javax.swing.JButton VidaYGolpes_J1;
    private javax.swing.JButton VidaYGolpes_J2;
    private javax.swing.JTextArea Vida_J1;
    private javax.swing.JTextArea Vida_J2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
    
    
}
